"""Export the seeded lab as a JS data file for the static GUI demo.

The GitHub Pages GUI runs with no backend, so it needs the seeded org plus enough
policy/ACL metadata to *recompute* onboarding and access decisions client-side.
This script dumps exactly that, generated from the real engine so the browser
demo and the Python truth can never drift.

    python scripts/export_snapshot.py   # writes docs/app/data.js
"""

from __future__ import annotations

import json
from pathlib import Path

from labsuite.models import PROXMOX_PRIVILEGES, AccessLevel, Department, ProxmoxRole
from labsuite.operations import SAAS_BASELINE, SAAS_CATALOG, SAAS_ROLE_APPS
from labsuite.policy import (
    BASELINE_GROUP,
    DEPARTMENT_GROUP,
    GATED_SHARES,
    IMAGE_CATALOG,
    ROLE_BLUEPRINTS,
    ROLE_IMAGE,
    ROLE_TRAININGS,
)
from labsuite.seed import DEMO_PASSWORD, build_lab

OUT = Path(__file__).resolve().parent.parent / "docs" / "app" / "data.js"


def main() -> None:
    cp = build_lab()

    users = []
    for u in sorted(cp.okta.list_users(), key=lambda x: x.username):
        users.append(
            {
                "username": u.username,
                "display_name": u.display_name,
                "email": u.email,
                "department": u.department.value,
                "title": u.title,
                "active": u.active,
                "okta_groups": sorted(cp.okta.groups_for(u.username)),
            }
        )

    ad_nesting = {
        g.name: sorted(g.member_groups)
        for g in cp.ad.groups.values()  # concrete access is fine in an export script
        if g.member_groups
    }

    shares = {}
    for s in cp.truenas.list_shares():
        shares[s.name] = {
            "dataset": s.dataset,
            "description": s.description,
            "sensitive": s.sensitive,
            "acl": {grp: int(lvl) for grp, lvl in s.acl.items()},
        }

    vms = {}
    for vm in cp.proxmox.list_vms():
        vms[str(vm.vmid)] = {"name": vm.name, "node": vm.node, "pool": vm.pool, "path": vm.path}

    proxmox_acl = [{"path": a.path, "group": a.group, "role": int(a.role)} for a in cp.proxmox.acl]

    image_catalog = {
        name: {**img.to_dict(), "security_summary": img.security_summary()}
        for name, img in IMAGE_CATALOG.items()
    }
    devices = [d.to_dict() for d in cp.endpoints.list_devices()]

    data = {
        "demo_password": DEMO_PASSWORD,
        "departments": [d.value for d in Department],
        "baseline_group": BASELINE_GROUP,
        "department_group": {d.value: g for d, g in DEPARTMENT_GROUP.items()},
        "role_blueprints": {
            name: {"description": bp.description, "extra_groups": list(bp.extra_groups)}
            for name, bp in ROLE_BLUEPRINTS.items()
        },
        "access_levels": {int(lvl): str(lvl) for lvl in AccessLevel},
        "proxmox_roles": {int(r): str(r) for r in ProxmoxRole},
        "proxmox_privileges": {p: int(r) for p, r in PROXMOX_PRIVILEGES.items()},
        "image_catalog": image_catalog,
        "role_image": dict(ROLE_IMAGE),
        "gated_shares": dict(GATED_SHARES),
        "role_trainings": dict(ROLE_TRAININGS),
        "saas_catalog": dict(SAAS_CATALOG),
        "saas_baseline": list(SAAS_BASELINE),
        "saas_role_apps": dict(SAAS_ROLE_APPS),
        "compliance_records": cp.compliance.all_records(),
        "operations": cp.ops.to_dict(),
        "users": users,
        "ad_nesting": ad_nesting,
        "shares": shares,
        "vms": vms,
        "proxmox_acl": proxmox_acl,
        "devices": devices,
    }

    banner = (
        "// AUTO-GENERATED by scripts/export_snapshot.py -- do not edit by hand.\n"
        "// A faithful snapshot of the seeded lab + policy metadata, so the static\n"
        "// GitHub Pages demo can recompute onboarding/access exactly like the engine.\n"
    )
    OUT.write_text(banner + "window.LABSUITE_DATA = " + json.dumps(data, indent=2) + ";\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
